version: '3'
services:
  base:
    build:
      context: .
      dockerfile: ./base/Dockerfile
    image: pmallozzi/ltltools:latest
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    image: pmallozzi/ltltools:web